config/routes.rb
Ratebeer::Application.routes.draw do
  resources :users


  resources :beers


  resources :breweries
	root :to => 'breweries#index'
	#get 'ratings', to: 'ratings#index'
 	get 'kaikki_bisset', to: 'beers#index'
 	#get 'ratings/new', to:'ratings#new'
 	#post 'ratings', to: 'ratings#create'
 	resources :ratings, :only => [:index, :new, :create, :destroy]
 	get 'signup', to: 'users#new'
 	resources :sessions, :only => [:new, :create, :destroy]
 	get 'signin', to: 'sessions#new'
	delete 'signout', to: 'sessions#destroy'
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  attr_accessible :name, :year
  has_many :beers
  has_many :ratings, :through => :beers
  validates :name, presence: true
  validates_numericality_of :year, { :greater_than_or_equal_to => 1042,
                                      :less_than_or_equal_to => 2013,
                                      :only_integer => true }
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

	before_filter :authenticate, :only => [:new, :create, :destroy]
  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
		#render :panimot
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breweries }
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(params[:brewery])

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render json: @brewery, status: :created, location: @brewery }
      else
        format.html { render action: "new" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(params[:brewery])
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end
  
  private

  def authenticate
  	admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}	
  	authenticate_or_request_with_http_basic do |username, password|
			not username.nil? and password == admin_accounts[username]
		end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>
<p> Number of breweries: <%= @breweries.count %> </p> 

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @breweries.each do |brewery| %>
  <tr>
    <td><%= link_to brewery.name, brewery_path(brewery) %></td>
    <td><%= brewery.year %></td>
    <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brewery', new_brewery_path %>
<%= link_to 'List of beers', beers_path %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
<%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
  <h2><%= @brewery.name %></h2>
</p>

<p>
  <em>Established year <%= @brewery.year %></em>
</p>

<p>
  <b>Beers:</b>
  <%= @brewery.beers.count %>
</p>

<p>
 <% @brewery.beers.each do |beer| %>
   <%= link_to beer.name, beer %>
 <% end %>
</p>

<p>
	<% if @brewery.ratings.empty? %>
		The brewery has no ratings yet.
	<% else %>
		The brewery has <%=pluralize(@brewery.ratings.count, 'rating')%>, average <%=@brewery.average_rating%>.
	<% end %>
</p>


<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>