config/routes.rb
Ratebeer::Application.routes.draw do
  resources :users


  resources :beers


  resources :breweries
	root :to => 'breweries#index'
	#get 'ratings', to: 'ratings#index'
 	get 'kaikki_bisset', to: 'beers#index'
 	#get 'ratings/new', to:'ratings#new'
 	#post 'ratings', to: 'ratings#create'
 	resources :ratings, :only => [:index, :new, :create, :destroy]
 	get 'signup', to: 'users#new'
 	resources :sessions, :only => [:new, :create, :destroy]
 	get 'signin', to: 'sessions#new'
	delete 'signout', to: 'sessions#destroy'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
	include RatingAverage
  attr_accessible :brewery_id, :name, :style
  
  belongs_to :brewery
  has_many :ratings, :dependent => :destroy
  has_many :raters, :through => :ratings, :source => :user
  validates :name, presence: true
  validates :style, presence: true
  
  def to_s
  	"Olut #{name}, panimo #{brewery.name}" 
  end
      	
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
		@breweries = Brewery.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new
		@breweries = Brewery.all
		@styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])
		@beers = Beer.all
    @breweries = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render json: @beer, status: :created, location: @beer }
      else
        format.html { render action: "new" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br />
    <%= f.number_field :brewery_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Style</th>
    <th>Brewery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beers.each do |beer| %>
  <tr>
    <td><%= link_to beer.name, beer %></td>
    <td><%= beer.style %></td>
    <td><%= link_to beer.brewery.name, beer.brewery %></td>
    <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
    <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer', new_beer_path %>
<%= link_to 'List of breweries', breweries_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer.name %>
</p>

<p>
  <b>Style:</b>
  <%= @beer.style %>
</p>

<p>
  <b>Brewery:</b>
  <%= @beer.brewery.name %>
</p>

<p>
	<% if @beer.ratings.empty? %>
		The beer has not yet been rated!
	<% else %>
		The beer has <%=pluralize(@beer.ratings.count, 'rating')%>, average <%=@beer.average_rating%>.
	<% end %>
</p>


<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>