config/routes.rb
Ratebeer::Application.routes.draw do
  resources :users


  resources :beers


  resources :breweries
	root :to => 'breweries#index'
	#get 'ratings', to: 'ratings#index'
 	get 'kaikki_bisset', to: 'beers#index'
 	#get 'ratings/new', to:'ratings#new'
 	#post 'ratings', to: 'ratings#create'
 	resources :ratings, :only => [:index, :new, :create, :destroy]
 	get 'signup', to: 'users#new'
 	resources :sessions, :only => [:new, :create, :destroy]
 	get 'signin', to: 'sessions#new'
	delete 'signout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Ratebeer</title>
  	<%= stylesheet_link_tag   			"application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	</head>
	<body>
		
		
		<% if not current_user.nil? %>
			<div class="navi">
		  	<%= link_to 'breweries', breweries_path %>
		  	<%= link_to 'beers', beers_path %>
		  	<%= link_to 'ratings', ratings_path %>
		  	<%= link_to 'users', users_path %>
		  	|
		  	<%= link_to current_user.username, user_path(current_user.id) %>
		  	<%= link_to 'rate a beer', new_rating_path %>
		  	<%= link_to 'signout', signout_path, :method => :delete %>
			</div>
  	
			<p><%= current_user.username %> signed in</p>
		<% else %>
			<div class="navi">
		  	<%= link_to 'breweries', breweries_path %>
		  	<%= link_to 'beers', beers_path %>
		  	<%= link_to 'ratings', ratings_path %>
		  	<%= link_to 'users', users_path %>
		  	|
		  	<%= link_to 'signin', signin_path  %>
		  	<%= link_to 'signup', signup_path %>
			</div>
		<% end %>

		<%= yield %>

	</body>
</html>